src/objects/Point__c.object
<CustomObject>
    <description>Initially, the Point object is populated from an embedded Factory class that generates and stores a sample set of Review Points. Larger sets of Review Points can be imported via the Apex Data Loader.</description>
    <label>Point</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Point Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Score__c.object
<CustomObject>
    <description>The Score object stores user-generated data unique to every org.</description>
    <fields>
        <fullName>Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Point</label>
        <referenceTo>Point__c</referenceTo>
        <relationshipLabel>Scores</relationshipLabel>
        <relationshipName>Scores</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Score</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GuideCtrl.cls
/**
 * Generates Study Guide for a particular Review Module for the Study Points with completed Scores.
 */
 public with sharing class GuideCtrl {
 
    public class GuideRow {
        public Point__c Point {get; set;}
        public Decimal Tries {get; set;}
        public String getResult() {
            if (Tries==1) { 
                return 'Correct'; 
            } else { 
                return 'Incorrect (' + String.valueOf(Tries) + 'x)';              
            }
        }
    }

    /**
     * Holds Points with Scores. 
     */ 
    public List<GuideRow> Rows { get; set; }
    
  
    /**
     * Selects Study Guide Module. Set via parameter ('module=').
     */
    public String Module { get; set; }
    
    /**
     * Presents number of Scores with multiple tries for the Study Guide Module.
     */
    public String Incorrect { get; set; }    
    
    /**
     * Presents number of Scores with a single tries for the Study Guide Module.
     */   
    public String Correct { get; set; }
    
    /**
     * Presents number of Points without Scores for the Study Guide Module.
     */
    public String Remaining { get; set; }
    
    /**
     * Sets module for study guide via a parameter. 
     */
    public GuideCtrl() {
        Module = System.currentPagereference().getParameters().get(Factory.PARAM_MODULE);
    }
    
    /**
     * Prepares properties for the current module for presentation on the study guide page.
     * Redirects to Main if there are no Scores for the selected module, 
     * or Scores__c object is not accessible.
     */
    public PageReference doModule() {
    
        Integer doneCount = 0; 
        Boolean isAccessible = Score__c.sObjectType.getDescribe().isAccessible();
        if (isAccessible) doneCount = Factory.doneCount(Module);      
        if (!isAccessible ||0==doneCount) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,
                Factory.ERROR_PENDING_NOT_SELECTED)); 
            return Page.Main;      
        }
    
        List<Point__c> correctPoints = Factory.getCorrect(Module);
        List<Point__c> incorrectPoints = Factory.getIncorrect(Module);
        
        Integer correctCount = correctPoints.size();
        Integer incorrectCount = incorrectPoints.size();
        
        Integer moduleCount = Factory.moduleCount(Module);
        Integer leftCount = moduleCount - doneCount ;
 
        Incorrect = String.valueOf(incorrectCount); 
        Correct = String.valueOf(correctCount);
        Remaining = String.valueOf(leftCount);
        
        Map<Id,Decimal> tries = Factory.getTries(Module);
        
        List<Point__c> ps = new List<Point__c>();
            ps.addAll(incorrectPoints);
            ps.addAll(correctPoints);
        
        List<GuideRow> rs = new List<GuideRow>();
        
        for (Point__c p : ps) {
            GuideRow row = new GuideRow();
            row.Point = p;
            row.Tries = tries.get(p.Id);   
            rs.add(row);     
        }
        
        Rows = rs;
        
        return null;
    }      
}